language: cpp

compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - apt-cache policy
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8 -std=c++11 -Wno-unused-local-typedefs" CC="gcc-4.8 -Wno-unused-local-typedefs"; fi
  - sudo apt-get install -qq cmake 
  - sudo apt-get install libgtest-dev
  - sudo apt-get install libboost1.55-all-dev #install all Boost libs
  - sudo apt-get install cmake # install cmake
  - sudo apt-get install libevent-dev automake libtool flex bison pkg-config g++ libssl-dev #install thrift deps
  
  - sudo wget http://mirrors.kernel.org/ubuntu/pool/universe/t/thrift-compiler/thrift-compiler_0.8.0-0ubuntu2_i386.deb
  - sudo dpkg -i thrift-compiler_0.8.0-0ubuntu2_i386.deb
  
  #- sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev #redundant boost devs
  - git clone https://github.com/apache/thrift.git
  #compiling thrift
  - cd thrift/lib/cpp
  #- ./bootstrap.sh
  #- ./configure --disable-more-warn --without-c_glib --without-hava --without-java --without-ruby --without-erlang
  #- sudo make compiler/cpp
  #- sudo make install compiler/cpp
  - sudo make 
  - sudo make install
  #- thrift -version
  #end compiling thrift
  #compiling gtest
  - pwd
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  # copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
  - sudo cp *.a /usr/lib
  #end compiling gtest
  # get yourself back to the right dir
  - cd /home/travis/build/sillsm/econix
  - sudo apt-get install openssl libssl-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - pwd

script: "make --debug=v && pwd && ./CppTesting -v"

notifications:
  email:
    - max.sills@gmail.com
  on_success: change
  on_failure: always
