language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake 

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - pwd

script: "make && pwd && sh ./.travis_build.sh && cd ../../test/ && sh ./.travis_build.sh"

notifications:
  email:
    - max.sills@gmail.com
  on_success: change
  on_failure: alwayss
